baseURL = "/"
languageCode = "en-us"
title = "Cyber Risk Quant"
theme = "hugo-paradigm"
enableGitInfo = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"
paginate = 6

[permalinks]
    post = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"
    work =  "works"
    author = "authors"
  
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
  
# Main Menu
[[menu.main]]
    name = "About us"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

[[menu.main]]
    name = "Contact us"
    url = "/contact/"
    weight = 3



# Footer Menu Primary
[[menu.footer_primary]]
	name = "Home"
	url = "/"
    weight = 1
[[menu.footer_primary]]
    name = "Blog"
    url = "/posts/"
    weight = 2
[[menu.footer_primary]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 3

# Footer Menu Secondary
[[menu.footer_secondary]]
    name = "Custom Page 1"
    url = "/custom-page-1/"
    weight = 1

[[menu.footer_secondary]]
    name = "Custom Page 2"
    url = "/custom-page-2/"
    weight = 2
[[menu.footer_secondary]]
    name = "Custom Page 3"
    url = "/custom-page-3/"
    weight = 3
